name: Build and Deploy Package Doc

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  docbuild:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash

      # Build the package documentaion
      - name: Build Package Documentation
        run: |
          jupyter-book build doc/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
